
version: 0.2

phases:
    PRE_BUILD:
        commands:
            - git clone git@github.com:duo-labs/cloudmapper.git
    BUILD:
        commands:
            - docker-compose build
            - accountname="demo" docker-compose up
    POST_BUILD:
        commands:
            - touch hello.js
artifacts:
    files:
        - ./hello.js
