
version: 0.2

phases:
    PRE_BUILD:
        commands:
            - git clone git@github.com:duo-labs/cloudmapper.git
            - echo "PRE_BUILD"
    BUILD:
        commands:
            - echo "TEST"
            - touch thing.txt
            - echo "Hello World" > thing.txt
            - aws s3api put-object --bucket dmiller-s3 --key testing/ --body thing.txt
artifacts:
    files:
        - "**/*"
