
version: 0.2

phases:
    PRE_BUILD:
        commands:
            - git clone git@github.com:duo-labs/cloudmapper.git
    BUILD:
        commands:
            - touch thing.txt
            - echo "Hello World" > thing.txt
artifacts:
    files:
        - "**/*"
